### ISSUE TITLE
LaTeX rendering for bar chart scaling factors

### ISSUE THREAD

**Issue by standage** [BrendelGroup/iLoci_Lai2020#28]
In cell 6 of `work/notebooks/make-F5-F6.ipynb`, if we replace

```python
bdf = bdf.rename(index = {'niLoci' : 'niLoci * 10',
                'ciLoci' : 'ciLoci * 1000', 'fiLoci' : 'fiLoci * 1000'})
```

with

```python
bdf = bdf.rename(index = {'niLoci' : 'niLoci $\times 10$',
                'ciLoci' : 'ciLoci $\times 1000$', 'fiLoci' : 'fiLoci $\times 1000$'})
```

it should render as expected. I don't have access to my dev environment at the moment to check, or else I would try it and submit a pull request.

I also suggest including a comment in the corresponding Figure legend indicating that these three columns are scaled up to improve visibility.

**Comment by vpbrendel** [comment]
Done.
